apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: formflow
type: Opaque
data:
  mysql-root-password: cm9vdA==  # base64 encoded value of 'root'
  mysql-database: Zm9ybWZsb3c=  # base64 encoded value of 'formflow'
