apiVersion: v1
kind: Service
metadata:
  name: formflowapi-service
  namespace: formflow
  labels:
    app: formflowapi
spec:
  selector:
    app: formflowapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

