apiVersion: v1
kind: Service
metadata:
  name: formflowapi-service
  namespace: formflow
  labels:
    app: formflowapi
spec:
  selector:
    app: formflowapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: formflowfront-service
  namespace: formflow
  labels:
    app: formflowfront
spec:
  selector:
    app: formflowfront
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

