apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: formflow
type: Opaque
data:
  mysql-password: cm9vdA==  # base64 encoded value of 'root'
  mysql-database: Zm9ybWZsb3c=  # base64 encoded value of 'formflow'

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqlserverdb-config
  namespace: formflow
data:
  ACCEPT_EULA: "Y"

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysqldb
  namespace: formflow
spec:
  serviceName: mysqlserverdb-service
  replicas: 1
  selector:
    matchLabels:
      app: mysqlserver
  template:
    metadata:
      labels:
        app: mysqlserver
    spec:
      containers:
      - name: mysqlserver
        image: mysql:latest
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-database
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: mysqlserverdb-service
  namespace: formflow
spec:
  type: LoadBalancer
  selector:
    app: mysqlserver
  ports:
  - port: 3306
    protocol: TCP
    name: mysql